import type { Customer, Lead, Task } from '@/types';

const CUSTOMER_SEED: Customer[] = [
  {
    id: 'cust-1',
    name: 'Acme Corporation',
    email: 'info@acme.com',
    phone: '(555) 123-4567',
    company: 'Acme Corporation',
    location: 'New York, NY',
    status: 'Active',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-01-15T08:00:00Z',
    notes: [
      {
        id: 'n1',
        content: 'Initial contact via LinkedIn. Interested in enterprise plan.',
        createdAt: '2025-01-15T08:00:00Z',
      },
    ],
  },
  {
    id: 'cust-2',
    name: 'TechStart Inc',
    email: 'hello@techstart.io',
    phone: '(555) 234-5678',
    company: 'TechStart Inc',
    location: 'San Francisco, CA',
    status: 'Active',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-02-10T10:30:00Z',
    notes: [],
  },
  {
    id: 'cust-3',
    name: 'Global Solutions',
    email: 'contact@globalsol.com',
    phone: '(555) 345-6789',
    company: 'Global Solutions',
    location: 'Chicago, IL',
    status: 'Active',
    assignedEmployeeId: 'emp-3',
    createdAt: '2025-03-05T14:00:00Z',
    notes: [],
  },
  {
    id: 'cust-4',
    name: 'BlueSky Logistics',
    email: 'ops@bluesky.com',
    phone: '(555) 456-7890',
    company: 'BlueSky Logistics',
    location: 'Dallas, TX',
    status: 'Inactive',
    assignedEmployeeId: 'emp-4',
    createdAt: '2024-11-20T09:00:00Z',
    notes: [],
  },
  {
    id: 'cust-5',
    name: 'Pinnacle Consulting',
    email: 'team@pinnacle.com',
    phone: '(555) 567-8901',
    company: 'Pinnacle Consulting',
    location: 'Boston, MA',
    status: 'Active',
    assignedEmployeeId: 'emp-5',
    createdAt: '2025-04-12T11:00:00Z',
    notes: [],
  },
];

const LEAD_SEED: Lead[] = [
  {
    id: 'lead-1',
    name: 'Meridian Corp',
    email: 'sales@meridian.com',
    phone: '(555) 678-9012',
    company: 'Meridian Corp',
    status: 'New',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-06-01T08:00:00Z',
  },
  {
    id: 'lead-2',
    name: 'Vantage Point',
    email: 'info@vantagepoint.com',
    phone: '(555) 789-0123',
    company: 'Vantage Point',
    status: 'Contacted',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-05-28T10:00:00Z',
  },
  {
    id: 'lead-3',
    name: 'Summit Health',
    email: 'exec@summithealth.com',
    phone: '(555) 890-1234',
    company: 'Summit Health',
    status: 'Follow-up',
    assignedEmployeeId: 'emp-3',
    createdAt: '2025-05-15T14:30:00Z',
  },
  {
    id: 'lead-4',
    name: 'BrightPath Media',
    email: 'team@brightpath.com',
    phone: '(555) 901-2345',
    company: 'BrightPath Media',
    status: 'Qualified',
    assignedEmployeeId: 'emp-4',
    createdAt: '2025-05-10T09:00:00Z',
  },
  {
    id: 'lead-5',
    name: 'Harborview',
    email: 'admin@harborview.com',
    phone: '(555) 012-3456',
    company: 'Harborview',
    status: 'New',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-06-10T16:00:00Z',
  },
];

const TASK_SEED: Task[] = [
  {
    id: 'task-1',
    title: 'Follow up with Acme Corp',
    description: 'Send the revised proposal and schedule a demo call.',
    assignedEmployeeId: 'emp-1',
    priority: 'High',
    dueDate: '2025-07-01',
    status: 'Todo',
    relatedCustomerId: 'cust-1',
    createdAt: '2025-06-15T08:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Prepare onboarding deck',
    description: 'Create onboarding slide deck for TechStart Inc.',
    assignedEmployeeId: 'emp-2',
    priority: 'Medium',
    dueDate: '2025-07-05',
    status: 'In Progress',
    relatedCustomerId: 'cust-2',
    createdAt: '2025-06-18T10:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Update CRM documentation',
    description: 'Refresh the CRM user guide with new features.',
    assignedEmployeeId: 'emp-3',
    priority: 'Low',
    dueDate: '2025-07-10',
    status: 'Todo',
    createdAt: '2025-06-20T14:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Review Q2 pipeline',
    description: 'Analyze lead conversion rates for the quarterly review.',
    assignedEmployeeId: 'emp-4',
    priority: 'High',
    dueDate: '2025-06-30',
    status: 'Completed',
    createdAt: '2025-06-01T09:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Schedule check-in with BlueSky',
    description: 'Reach out to the inactive customer for renewal discussion.',
    assignedEmployeeId: 'emp-5',
    priority: 'Medium',
    dueDate: '2025-07-03',
    status: 'Todo',
    relatedCustomerId: 'cust-4',
    createdAt: '2025-06-22T11:00:00Z',
  },
];

export function getSeedState() {
  return {
    customers: {
      ids: CUSTOMER_SEED.map((c) => c.id),
      entities: Object.fromEntries(CUSTOMER_SEED.map((c) => [c.id, c])),
    },
    leads: {
      ids: LEAD_SEED.map((l) => l.id),
      entities: Object.fromEntries(LEAD_SEED.map((l) => [l.id, l])),
    },
    tasks: {
      ids: TASK_SEED.map((t) => t.id),
      entities: Object.fromEntries(TASK_SEED.map((t) => [t.id, t])),
    },
  };
}
