const CUSTOMERS = [
  {
    id: 'cust-1',
    name: 'Acme Corporation',
    email: 'info@acme.com',
    phone: '(555) 123-4567',
    company: 'Acme Corporation',
    location: 'New York, NY',
    status: 'Active',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-01-15T08:00:00Z',
    notes: [
      {
        id: 'n1',
        content: 'Initial contact via LinkedIn. Interested in enterprise plan.',
        createdAt: '2025-01-15T08:00:00Z',
      },
    ],
  },
  {
    id: 'cust-2',
    name: 'TechStart Inc',
    email: 'hello@techstart.io',
    phone: '(555) 234-5678',
    company: 'TechStart Inc',
    location: 'San Francisco, CA',
    status: 'Active',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-02-10T10:30:00Z',
    notes: [],
  },
  {
    id: 'cust-3',
    name: 'Global Solutions',
    email: 'contact@globalsol.com',
    phone: '(555) 345-6789',
    company: 'Global Solutions',
    location: 'Chicago, IL',
    status: 'Active',
    assignedEmployeeId: 'emp-3',
    createdAt: '2025-03-05T14:00:00Z',
    notes: [],
  },
  {
    id: 'cust-4',
    name: 'BlueSky Logistics',
    email: 'ops@bluesky.com',
    phone: '(555) 456-7890',
    company: 'BlueSky Logistics',
    location: 'Dallas, TX',
    status: 'Inactive',
    assignedEmployeeId: 'emp-4',
    createdAt: '2024-11-20T09:00:00Z',
    notes: [],
  },
  {
    id: 'cust-5',
    name: 'Pinnacle Consulting',
    email: 'team@pinnacle.com',
    phone: '(555) 567-8901',
    company: 'Pinnacle Consulting',
    location: 'Boston, MA',
    status: 'Active',
    assignedEmployeeId: 'emp-5',
    createdAt: '2025-04-12T11:00:00Z',
    notes: [],
  },
  {
    id: 'cust-6',
    name: 'NovaTech Solutions',
    email: 'hello@novatech.com',
    phone: '(555) 678-9012',
    company: 'NovaTech Solutions',
    location: 'Seattle, WA',
    status: 'Active',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-01-28T09:15:00Z',
    notes: [
      {
        id: 'n2',
        content: 'Referred by Acme Corporation. Looking for CRM integration.',
        createdAt: '2025-01-28T09:15:00Z',
      },
    ],
  },
  {
    id: 'cust-7',
    name: 'Evergreen Enterprises',
    email: 'admin@evergreen.com',
    phone: '(555) 789-0123',
    company: 'Evergreen Enterprises',
    location: 'Portland, OR',
    status: 'Active',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-02-18T13:45:00Z',
    notes: [],
  },
  {
    id: 'cust-8',
    name: 'Silverline Finance',
    email: 'contact@silverline.com',
    phone: '(555) 890-1234',
    company: 'Silverline Finance',
    location: 'Austin, TX',
    status: 'Active',
    assignedEmployeeId: 'emp-3',
    createdAt: '2025-03-22T10:00:00Z',
    notes: [],
  },
  {
    id: 'cust-9',
    name: 'Crestview Media',
    email: 'info@crestview.com',
    phone: '(555) 901-2345',
    company: 'Crestview Media',
    location: 'Los Angeles, CA',
    status: 'Inactive',
    assignedEmployeeId: 'emp-4',
    createdAt: '2024-10-05T08:30:00Z',
    notes: [],
  },
  {
    id: 'cust-10',
    name: 'Atlas Industries',
    email: 'sales@atlas.com',
    phone: '(555) 012-3456',
    company: 'Atlas Industries',
    location: 'Detroit, MI',
    status: 'Active',
    assignedEmployeeId: 'emp-5',
    createdAt: '2025-04-01T15:20:00Z',
    notes: [],
  },
  {
    id: 'cust-11',
    name: 'Summit Healthcare',
    email: 'ops@summithealth.com',
    phone: '(555) 111-2222',
    company: 'Summit Healthcare',
    location: 'Denver, CO',
    status: 'Active',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-05-10T11:00:00Z',
    notes: [
      {
        id: 'n3',
        content:
          'Healthcare compliance requirements discussed. Need HIPAA-compliant solution.',
        createdAt: '2025-05-10T11:00:00Z',
      },
    ],
  },
  {
    id: 'cust-12',
    name: 'Rivera & Associates',
    email: 'contact@rivera.com',
    phone: '(555) 222-3333',
    company: 'Rivera & Associates',
    location: 'Miami, FL',
    status: 'Active',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-05-22T09:30:00Z',
    notes: [],
  },
  {
    id: 'cust-13',
    name: 'ClearView Analytics',
    email: 'hello@clearview.com',
    phone: '(555) 333-4444',
    company: 'ClearView Analytics',
    location: 'Atlanta, GA',
    status: 'Inactive',
    assignedEmployeeId: 'emp-3',
    createdAt: '2024-09-15T14:00:00Z',
    notes: [],
  },
  {
    id: 'cust-14',
    name: 'Iron Peak Construction',
    email: 'info@ironpeak.com',
    phone: '(555) 444-5555',
    company: 'Iron Peak Construction',
    location: 'Phoenix, AZ',
    status: 'Active',
    assignedEmployeeId: 'emp-4',
    createdAt: '2025-06-01T08:45:00Z',
    notes: [],
  },
  {
    id: 'cust-15',
    name: 'Lighthouse Education',
    email: 'team@lighthouseedu.com',
    phone: '(555) 555-6666',
    company: 'Lighthouse Education',
    location: 'Nashville, TN',
    status: 'Inactive',
    assignedEmployeeId: 'emp-5',
    createdAt: '2024-12-10T16:00:00Z',
    notes: [],
  },
];

const LEADS = [
  {
    id: 'lead-1',
    name: 'Meridian Corp',
    email: 'sales@meridian.com',
    phone: '(555) 678-9012',
    company: 'Meridian Corp',
    status: 'New',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-06-01T08:00:00Z',
  },
  {
    id: 'lead-2',
    name: 'Vantage Point',
    email: 'info@vantagepoint.com',
    phone: '(555) 789-0123',
    company: 'Vantage Point',
    status: 'Contacted',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-05-28T10:00:00Z',
  },
  {
    id: 'lead-3',
    name: 'Summit Health',
    email: 'exec@summithealth.com',
    phone: '(555) 890-1234',
    company: 'Summit Health',
    status: 'Follow-up',
    assignedEmployeeId: 'emp-3',
    createdAt: '2025-05-15T14:30:00Z',
  },
  {
    id: 'lead-4',
    name: 'BrightPath Media',
    email: 'team@brightpath.com',
    phone: '(555) 901-2345',
    company: 'BrightPath Media',
    status: 'Qualified',
    assignedEmployeeId: 'emp-4',
    createdAt: '2025-05-10T09:00:00Z',
  },
  {
    id: 'lead-5',
    name: 'Harborview',
    email: 'admin@harborview.com',
    phone: '(555) 012-3456',
    company: 'Harborview',
    status: 'New',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-06-10T16:00:00Z',
  },
  {
    id: 'lead-6',
    name: 'Pinnacle Dynamics',
    email: 'contact@pinnacle-dyn.com',
    phone: '(555) 111-2222',
    company: 'Pinnacle Dynamics',
    status: 'Contacted',
    assignedEmployeeId: 'emp-3',
    createdAt: '2025-06-05T11:30:00Z',
  },
  {
    id: 'lead-7',
    name: 'Zenith Software',
    email: 'sales@zenithsoft.com',
    phone: '(555) 222-3333',
    company: 'Zenith Software',
    status: 'New',
    assignedEmployeeId: 'emp-5',
    createdAt: '2025-06-12T09:00:00Z',
  },
  {
    id: 'lead-8',
    name: 'Crossroads Logistics',
    email: 'ops@crossroads.com',
    phone: '(555) 333-4444',
    company: 'Crossroads Logistics',
    status: 'Follow-up',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-05-20T13:15:00Z',
  },
  {
    id: 'lead-9',
    name: 'Apex Manufacturing',
    email: 'info@apexmfg.com',
    phone: '(555) 444-5555',
    company: 'Apex Manufacturing',
    status: 'Qualified',
    assignedEmployeeId: 'emp-4',
    createdAt: '2025-05-08T08:45:00Z',
  },
  {
    id: 'lead-10',
    name: 'Greenfield Partners',
    email: 'hello@greenfield.com',
    phone: '(555) 555-6666',
    company: 'Greenfield Partners',
    status: 'Converted',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-04-15T10:00:00Z',
  },
  {
    id: 'lead-11',
    name: 'Coastal Ventures',
    email: 'team@coastalv.com',
    phone: '(555) 666-7777',
    company: 'Coastal Ventures',
    status: 'Contacted',
    assignedEmployeeId: 'emp-3',
    createdAt: '2025-06-08T14:30:00Z',
  },
  {
    id: 'lead-12',
    name: 'NorthStar Analytics',
    email: 'sales@northstar.com',
    phone: '(555) 777-8888',
    company: 'NorthStar Analytics',
    status: 'Follow-up',
    assignedEmployeeId: 'emp-5',
    createdAt: '2025-05-25T09:00:00Z',
  },
  {
    id: 'lead-13',
    name: 'Redwood Systems',
    email: 'contact@redwoodsys.com',
    phone: '(555) 888-9999',
    company: 'Redwood Systems',
    status: 'Lost',
    assignedEmployeeId: 'emp-2',
    createdAt: '2025-04-20T11:00:00Z',
  },
  {
    id: 'lead-14',
    name: 'Eagle Eye Security',
    email: 'info@eagleeye.com',
    phone: '(555) 999-0000',
    company: 'Eagle Eye Security',
    status: 'Converted',
    assignedEmployeeId: 'emp-4',
    createdAt: '2025-04-10T15:00:00Z',
  },
  {
    id: 'lead-15',
    name: 'Cascade Digital',
    email: 'hello@cascadedigital.com',
    phone: '(555) 000-1111',
    company: 'Cascade Digital',
    status: 'New',
    assignedEmployeeId: 'emp-1',
    createdAt: '2025-06-15T08:30:00Z',
  },
];

const TASKS = [
  {
    id: 'task-1',
    title: 'Follow up with Acme Corp',
    description: 'Send the revised proposal and schedule a demo call.',
    assignedEmployeeId: 'emp-1',
    priority: 'High',
    dueDate: '2025-07-01',
    status: 'Todo',
    relatedCustomerId: 'cust-1',
    createdAt: '2025-06-15T08:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Prepare onboarding deck',
    description: 'Create onboarding slide deck for TechStart Inc.',
    assignedEmployeeId: 'emp-2',
    priority: 'Medium',
    dueDate: '2025-07-05',
    status: 'In Progress',
    relatedCustomerId: 'cust-2',
    createdAt: '2025-06-18T10:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Update CRM documentation',
    description: 'Refresh the CRM user guide with new features.',
    assignedEmployeeId: 'emp-3',
    priority: 'Low',
    dueDate: '2025-07-10',
    status: 'Todo',
    createdAt: '2025-06-20T14:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Review Q2 pipeline',
    description: 'Analyze lead conversion rates for the quarterly review.',
    assignedEmployeeId: 'emp-4',
    priority: 'High',
    dueDate: '2025-06-30',
    status: 'Completed',
    createdAt: '2025-06-01T09:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Schedule check-in with BlueSky',
    description: 'Reach out to the inactive customer for renewal discussion.',
    assignedEmployeeId: 'emp-5',
    priority: 'Medium',
    dueDate: '2025-07-03',
    status: 'Todo',
    relatedCustomerId: 'cust-4',
    createdAt: '2025-06-22T11:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Send contract to NovaTech',
    description: 'Draft and send the service agreement for NovaTech Solutions.',
    assignedEmployeeId: 'emp-1',
    priority: 'High',
    dueDate: '2025-07-08',
    status: 'In Progress',
    relatedCustomerId: 'cust-6',
    createdAt: '2025-06-25T09:30:00Z',
  },
  {
    id: 'task-7',
    title: 'Conduct product demo',
    description: 'Demo the CRM platform to Evergreen Enterprises stakeholders.',
    assignedEmployeeId: 'emp-2',
    priority: 'Medium',
    dueDate: '2025-07-12',
    status: 'Todo',
    relatedCustomerId: 'cust-7',
    createdAt: '2025-06-28T14:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Follow up on Silverline proposal',
    description:
      'Check if Silverline Finance has reviewed the pricing proposal.',
    assignedEmployeeId: 'emp-3',
    priority: 'Low',
    dueDate: '2025-07-15',
    status: 'Todo',
    relatedCustomerId: 'cust-8',
    createdAt: '2025-06-29T10:15:00Z',
  },
  {
    id: 'task-9',
    title: 'Prepare monthly sales report',
    description:
      'Compile June sales data and conversion metrics for management.',
    assignedEmployeeId: 'emp-4',
    priority: 'High',
    dueDate: '2025-07-02',
    status: 'In Progress',
    createdAt: '2025-06-26T08:00:00Z',
  },
  {
    id: 'task-10',
    title: 'Update Atlas integration plan',
    description:
      'Revise the integration roadmap based on Atlas Industries feedback.',
    assignedEmployeeId: 'emp-5',
    priority: 'Medium',
    dueDate: '2025-07-18',
    status: 'Completed',
    relatedCustomerId: 'cust-10',
    createdAt: '2025-06-10T11:00:00Z',
  },
  {
    id: 'task-11',
    title: 'Onboard Summit Healthcare',
    description: 'Complete the onboarding checklist for Summit Healthcare.',
    assignedEmployeeId: 'emp-1',
    priority: 'High',
    dueDate: '2025-07-20',
    status: 'In Progress',
    relatedCustomerId: 'cust-11',
    createdAt: '2025-06-30T13:00:00Z',
  },
  {
    id: 'task-12',
    title: 'Schedule training session',
    description: 'Arrange CRM training for Rivera & Associates team.',
    assignedEmployeeId: 'emp-2',
    priority: 'Low',
    dueDate: '2025-07-25',
    status: 'Todo',
    relatedCustomerId: 'cust-12',
    createdAt: '2025-07-01T09:00:00Z',
  },
  {
    id: 'task-13',
    title: 'Audit inactive accounts',
    description:
      'Review all inactive customers and prepare re-engagement emails.',
    assignedEmployeeId: 'emp-3',
    priority: 'Medium',
    dueDate: '2025-07-08',
    status: 'Completed',
    createdAt: '2025-06-15T10:00:00Z',
  },
  {
    id: 'task-14',
    title: 'Finalize Q3 targets',
    description:
      'Set quarterly sales targets based on current pipeline analysis.',
    assignedEmployeeId: 'emp-4',
    priority: 'High',
    dueDate: '2025-07-05',
    status: 'Completed',
    createdAt: '2025-06-20T08:30:00Z',
  },
  {
    id: 'task-15',
    title: 'Review NPS survey results',
    description:
      'Analyze customer satisfaction scores and prepare action items.',
    assignedEmployeeId: 'emp-5',
    priority: 'Low',
    dueDate: '2025-07-22',
    status: 'In Progress',
    createdAt: '2025-07-02T14:30:00Z',
  },
];

function toEntityMap<T extends { id: string }>(items: T[]) {
  return {
    ids: items.map((i) => i.id),
    entities: Object.fromEntries(items.map((i) => [i.id, i])),
  };
}

export const ADMIN_USER = {
  id: 'user-1',
  email: 'admin@circlecrm.com',
  name: 'Admin User',
  role: 'admin' as const,
};

export const SALES_USER = {
  id: 'user-2',
  email: 'sales@circlecrm.com',
  name: 'Sales User',
  role: 'sales' as const,
};

export function buildSeedPayload() {
  return {
    version: 1,
    timestamp: Date.now(),
    customers: toEntityMap(CUSTOMERS),
    leads: toEntityMap(LEADS),
    tasks: toEntityMap(TASKS),
    auth: { user: ADMIN_USER, isAuthenticated: true },
    ui: { theme: 'light' as const },
    activity: { ids: [], entities: {} },
  };
}

export function buildAuthPayload(user: typeof ADMIN_USER = ADMIN_USER) {
  return {
    version: 1,
    timestamp: Date.now(),
    customers: { ids: [], entities: {} },
    leads: { ids: [], entities: {} },
    tasks: { ids: [], entities: {} },
    auth: { user, isAuthenticated: true },
    ui: { theme: 'light' as const },
    activity: { ids: [], entities: {} },
  };
}

export function buildEmptyPayload() {
  return {
    version: 1,
    timestamp: Date.now(),
    customers: { ids: [], entities: {} },
    leads: { ids: [], entities: {} },
    tasks: { ids: [], entities: {} },
    auth: { user: null, isAuthenticated: false },
    ui: { theme: 'light' as const },
    activity: { ids: [], entities: {} },
  };
}

export { CUSTOMERS, LEADS, TASKS };
